---
apiVersion: v1
kind: Pod
metadata:
  name: sample-env-pod
spec:
  containers:
  - name: sample-env-pod
    image: redis
    env:
    - name:  SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: samplesecret
          key: username

    - name:  SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: samplesecret
          key: password
  restartPolicy: Never