apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Some config"
  drink: {{ .Values.favourite.drink | default "tea" | quote }}
  food: {{ .Values.favourite.food | upper | quote }}