apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-busybox
spec:
  selector:
    matchLabels:
      app: nfs-busybox
  template:
    metadata:
      labels:
        app: nfs-busybox
    spec:
      containers:
      - name: nfs-busybox
        image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        volumeMounts:
          - mountPath: '/mnt'
            name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
