apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
spec:
  selector:
    matchLabels:
      app: nfs-web
  template:
    metadata:
      labels:
        app: nfs-web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nfs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
