apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: '/'
    server: 10.110.229.146
