---
- name: copy the nginx config file
  copy:
    src: files/static_site.cfg
    dest: /etc/nginx/sites-available/static_site.cfg
  become: yes

- name: create symlink
  file:
    src: /etc/nginx/sites-available/static_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes

- name: copy the content of the web site
  copy:
    src: files/static-site-src/
    dest: /home/ubuntu/static-site
  notify:
  - restart nginx
