---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: false

  vars:
    region: us-east-1
    instance_type: t2.micro
    ami: ami-0a313d6098716f372
    keypair: chef

  tasks:
    # - name: Setting up security group
    #   ec2_group:
    #     name: instance1_sg
    #     description: Rules Allowing traffic
    #     region: "{{ region }}"
    #     rules:
    #       - proto: tcp
    #         from_port: 80
    #         to_port: 80
    #         cidr_ip: 0.0.0.0/0
    #       - proto: tcp
    #         from_port: 22
    #         to_port: 22
    #         cidr_ip: 0.0.0.0/0
    #     rules_egress:
    #       - proto: all
    #         cidr_ip: 0.0.0.0/0

    - name: Create an ec2 instance
      ec2:
        key_name: "{{ keypair }}"
        group: default
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 1
        count_tag:
          Name: instance2-node
        instance_tags:
          Name: instance2-node
        vpc_subnet_id: subnet-4e5f6613
        assign_public_ip: yes
      register: ec2_out

    - name: Wait for ssh to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'
